requests.exceptions.SSLError: HTTPSConnectionPool(host='142.107.6.177', port=443): Max retries exceeded with url: /api (Caused by SSLError(SSLCertVerificationE
